"""backend/config/settings.py — module-level constants."""

DB_PATH = "data/stocks.db"
HISTORY_DAYS = 730
INITIAL_CAPITAL = 1_000_000
BENCHMARK_TICKER = "^NSEI"

DEFAULT_WATCHLIST = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "ICICIBANK.NS",
    "HINDUNILVR.NS", "SBIN.NS", "BHARTIARTL.NS", "BAJFINANCE.NS", "KOTAKBANK.NS",
    "LT.NS", "ASIANPAINT.NS", "AXISBANK.NS", "MARUTI.NS", "TITAN.NS",
    "NESTLEIND.NS", "WIPRO.NS", "ULTRACEMCO.NS", "HCLTECH.NS", "SUNPHARMA.NS",
]
